import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/navbar";
import Menu from './components/menu'
import StoreProvider from "./StoreProvider";
export const metadata: Metadata = {
  title: "hosthealth",
  description: "Generated by Lyndell Dobluis",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar />
        <Menu />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
